one moar try

diff --git a/.github/workflows/render-cv.yml b/.github/workflows/render-cv.yml
--- a/.github/workflows/render-cv.yml
+++ b/.github/workflows/render-cv.yml
@@ -37,13 +37,13 @@ jobs:
             echo "No RenderCV config directory found!"
             exit 1
           fi
-          settings=$(find $rendercv_dir -maxdepth 1 -type f \( -name "settings.yaml" -o -name "settings.yml" \))
-          if [ -z "$settings" ]; then
-            echo "Missing RenderCV config file!"
-            exit 1
-          fi
+          #settings=$(find $rendercv_dir -maxdepth 1 -type f \( -name "settings.yaml" -o -name "settings.yml" \))
+          #if [ -z "$settings" ]; then
+          #  echo "Missing RenderCV config file!"
+          #  exit 1
+          #fi
           #rendercv render $cv_file --settings $settings
-          rendercv render _data/cv.yml --settings $settings
+          rendercv render _data/cv.yml --settings assets/rendercv/settings.yaml
           rm assets/rendercv/rendercv_output/*.typ
       - name: Upload rendercv_output as an artifact
         uses: actions/upload-artifact@v4
