revert changes

diff --git a/.github/workflows/render-cv.yml b/.github/workflows/render-cv.yml
--- a/.github/workflows/render-cv.yml
+++ b/.github/workflows/render-cv.yml
@@ -27,23 +27,22 @@ jobs:
           pip install -r requirements.txt
       - name: RenderCV
         run: |
-          #cv_file=$(find _data  -maxdepth 1 -type f \( -name "cv.yaml" -o -name "cv.yml" \))
-          #if [ -z "$cv_file" ]; then
-          #  echo "No cv.yml file found!"
-          #  exit 1
-          #fi
+          cv_file=$(find _data  -maxdepth 1 -type f \( -name "cv.yaml" -o -name "cv.yml" \))
+          if [ -z "$cv_file" ]; then
+            echo "No cv.yml file found!"
+            exit 1
+          fi
           rendercv_dir=$(find assets -maxdepth 1 -type d -name "rendercv")
           if [ -z "$rendercv_dir" ]; then
             echo "No RenderCV config directory found!"
             exit 1
           fi
-          #settings=$(find $rendercv_dir -maxdepth 1 -type f \( -name "settings.yaml" -o -name "settings.yml" \))
-          #if [ -z "$settings" ]; then
-          #  echo "Missing RenderCV config file!"
-          #  exit 1
-          #fi
-          #rendercv render $cv_file --settings $settings
-          rendercv render _data/cv.yml --settings assets/rendercv/settings.yaml
+          settings=$(find $rendercv_dir -maxdepth 1 -type f \( -name "settings.yaml" -o -name "settings.yml" \))
+          if [ -z "$settings" ]; then
+            echo "Missing RenderCV config file!"
+            exit 1
+          fi
+          rendercv render $cv_file --settings $settings
           rm assets/rendercv/rendercv_output/*.typ
       - name: Upload rendercv_output as an artifact
         uses: actions/upload-artifact@v4
